//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVentaNelson.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venta
    {
        public int iDVenta { get; set; }
        public Nullable<int> iDDocumento { get; set; }
        public Nullable<int> iDCliente { get; set; }
        public Nullable<int> iDUsuario { get; set; }
        public Nullable<int> iDProducto { get; set; }
        public Nullable<decimal> totalVenta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
